### ISSUE TITLE
[Feature Request] Option to remove message when logging in

### ISSUE THREAD

**Issue by caggabeparty** [Xruptor/LootRollMover#11]
As the title says I'd like if it was possible to disable the message on startup, it's a bit annoying  always having that message in chat when it doesn't really provide much information for daily use.
![image](https://github.com/user-attachments/assets/47bb645b-7b58-4c3e-a481-3a0ed747c800)

**Comment by Xruptor** [comment]
I actually did this recently with another addon of mine.  I'll see about adding it.
