### ISSUE TITLE
"Rare Item" pick-up frame doesn't move when in raids

### ISSUE THREAD

**Issue by F-Lambda** [Xruptor/LootRollMover#12]
Don't know what the proper name for it is, but the "Rare Item" frame that appears when you get a blue or higher works properly when doing open world activities. When inside a raid, though, it resets to the default position in the center of the screen.

What's weird is that the actual Roll frame does still move properly when in a raid.

Edit: Seem's like it may actually be a conflict with Krowi's Achievement Filter, where moving achievement and event popups through it causes loot popups through this to reset position (even after disabling KAF). If LRM is applied most recently by editing its anchor, though, everything seems to works properly with both addons. A possible fix could be to reapply the LRM anchor setting on reload, to make sure it's the one applied most recently.

**Comment by Xruptor** [comment]
Wow that is weird indeed!  I wonder if they moved the frames or changed how they are handled.  It's possible the rare loot frames are separate now from the group that I usually hook into.  I'll take a look.

**Comment by Xruptor** [comment]
If you take a look at this post:
https://www.wowinterface.com/forums/showthread.php?t=58990

The user mentions three different types of popups.  LootRollMover only does the loot rolls and bonus loot roll that shows up.  If what you are talking about are the alert frames, which is the third picture in that post.  Those aren't actually loot frames, those are toast frames, which are the same like when you get an achievement.  They aren't associated with the loot frames at all and LootRollMover doesn't move those.  Please let me know if that's what you were talking about?

I do have an addon that moves AlertFrames called xanAchievementMover  (https://github.com/Xruptor/xanAchievementMover) (https://www.wowinterface.com/downloads/info21087-xanAchievementMover.html)

1) https://gyazo.com/7e8d2b88b8d176e8010cda4e5f56ce56
![image](https://github.com/user-attachments/assets/1593dbdc-2bb4-4348-a845-19a86fa661a1)


2) https://gyazo.com/e553b20580cab9b8fc62e3b4dba4df1e
![image](https://github.com/user-attachments/assets/1da1c8cc-b99a-4795-889e-89c5c142339a)


3) https://gyazo.com/f40e71c3001c9cfd91c8551ab5268848
![image](https://github.com/user-attachments/assets/b702941d-1fe1-4ade-8f2b-3d21aad48f5a)

**Comment by Xruptor** [comment]
It's been 2 weeks.  I still haven't heard a response back from you @F-Lambda 😄
