### ISSUE TITLE
loot roll frame bugs out in pre patch wotlk

### ISSUE THREAD

**Issue by Zankom** [Xruptor/LootRollMover#5]
its recently been not allowing me to roll need or greed just pass on most items, and sometimes the frame bugs out and displays a fortitude enchant that cant be gotten rid of even when reloading

**Comment by Zankom** [comment]
i disabled this addon it and was able to roll for loot fine

**Comment by Xruptor** [comment]
Alright then I'll see what could be causing the conflict then.

**Comment by Xruptor** [comment]
Okay it looks like they completely updated their Alert Systems.... again.  So I'll need to see how they are being generated and fired before I can actually move the AchievementFrame.

https://github.com/tomrus88/BlizzardInterfaceCode/blob/e2b884c714b3e751a9ec84b89a5fda964f35da05/Interface/FrameXML/AlertFrameSystems.lua

Examples of changes:

```
LootAlertFrame 

LootAlertSystem = AlertFrame:AddQueuedAlertFrameSubSystem("LootWonAlertFrameTemplate", LootWonAlertFrame_SetUp, 6, math.huge);

```

```
AchievementAlertSystem = AlertFrame:AddQueuedAlertFrameSubSystem("AchievementAlertFrameTemplate", AchievementAlertFrame_SetUp, 2, 6);
AchievementAlertSystem:SetCanShowMoreConditionFunc(function() return not C_PetBattles.IsInBattle() end);
```
