### ISSUE TITLE
Not working it seems or I'm doing something wrong

### ISSUE THREAD

**Issue by Galthariel** [Xruptor/LootRollMover#6]
The first time I used the addon by typing /lrm anchor he was around the middle of the screen I just moved it a bit up for testing purposes and that was it. About an hour after I went to Antorus Raid for a Mount run and guess what? The Loot Frame was centered at the bottom just above my Action Bars which I believe is the standard Blizz place.  Like I said could be me doing something wrong but since there is no lock position option I assumed that by leaving the addon it would be saved.

**Comment by Xruptor** [comment]
Hmm that is odd! It should be working as I have it installed and it's working fine for me.  All you need to do is move the anchor around then right click it or turn it back off.  It should remove the location and move the loot frame that to that position.  If it's not working it could be possible another addon is resetting the position or not allowing LootRollMover to move it.  Hmm... do a few checks on your end and I'll do it on mine as well to ensure it's working.

**Comment by Galthariel** [comment]
Check this out

![2022-11-25_13-48-04](https://user-images.githubusercontent.com/51491805/204069666-0febd77f-2b09-4104-bc03-9e2287930794.png)

**Comment by Xruptor** [comment]
Thanks!  Hmm... I will try it using other addons to see if there is a possibility something is conflicting with it.  I'm assuming you use ElvUI or some other custom UI addons?  Either way I'll do more testing on my end.

**Comment by Xruptor** [comment]
Okay so I tested it out using various characters and doing LFR and what not.  It's working for me.  It moves only the Loot Roll window to the location of the anchor. There are other windows that may popup not associated with Loot Rolls.  It could be Achievements or Progression alerts for other things.  This addon only moves the Loot Roll window that has the "Need, Greed, Pass" icons.

**Comment by Xruptor** [comment]
Unless you are using a custom Addon interface that has support for this (ElvUI, TukUI, etc..), it should be working.  I'm going to close the ticket for the time being since I cannot reproduce this issue.

**Comment by Galthariel** [comment]
Tks. That's exactly the same window / frame we're talking about. I even disabled the other two addons related to LootRools (PHL and PLR) since both aren't working properly anyways meaning that the only addon that is enabled it's yours. Don't know if is relevant or not it seems to happen only in Antorus Raid

**Comment by Xruptor** [comment]
Hmmm perhaps that raid is using some other windows that I'm not aware of.  I'll take a look at it myself when I get a chance to see what's going on.  Though I have been unable to reproduce the issue on my end.
