### ISSUE TITLE
Makes loot roll not appear

### ISSUE THREAD

**Issue by wheatbread** [Xruptor/LootRollMover#7]
Hi, came to report that the loot roll window did not appear for me at all with this installed.  I typed /lrm reset to move it back  in case it had somehow gone offscreen, but no dice.   I  had to disable the addon and reload before the loot roll window would appear.

**Comment by Xruptor** [comment]
Apparently they made some changes to the loot system from what I can see.  One of the many problems with being an addon author.  They are constantly working their framework and breaking stuff.

**Comment by Xruptor** [comment]
I think I figured out the issue.  Let me know if the next update fixes the issue.
