### ISSUE TITLE
Include Bonus Roll Frame

### ISSUE THREAD

**Issue by Kanegasi** [Xruptor/LootRollMover#9]
Would you mind including the BonusRollFrame from previous expansions in the same anchor spot? That also likes to appear over my bars.

**Comment by Xruptor** [comment]
That's totally weird, I thought it would have captured that frame from previous expansions since they share the same loot base?  Hmm.... that's really odd.  Do you play on retail or WOTLK/Classic?

**Comment by Kanegasi** [comment]
I'm on retail. I went through a Pandaria world boss run and the bonus roll frame was not at the anchor position I set.

You're correct, they share the same frame base and BonusRollFrame is even defined and controlled in FrameXML\GroupLootFrame.lua, but they are separate frames. You only deal with `GroupLootFrame1`, etc in your code, you'll have to add `BonusRollFrame`.

**Comment by Xruptor** [comment]
Ah okay originally I think they were ancored to GroupLootFrame.  Perhaps they changed that.

**Comment by Xruptor** [comment]
I added the  BonusRollFrame in the latest update.
https://github.com/Xruptor/LootRollMover/commit/bb950359a21da4a103da91458cd49a841b822956

https://github.com/Xruptor/LootRollMover/releases/tag/v5.6
